jobs:
  - name: retriable_job
    type: runSh
    allowPublicAccess: true
    steps:
      - TASK:
          runtime:
            options:
              env:
                - max_retries: 3
          script:
            # simulate job failure
            - cat phantom_file.sh
    on_success:
      script:
        #reset failure counter
        - shipctl post_resource_state $JOB_NAME failure_counter 0
    on_failure:
      script:
        - counterVal=$(shipctl get_resource_state "failure_counter") 
        - |
          if [ "$counterVal" -eq "$max_retries" ]
          then
              # reset counter and do nothing
              shipctl post_resource_state $JOB_NAME failure_counter 0
          else
              # increment failure counter
              let "counterVal++"
              shipctl post_resource_state $JOB_NAME failure_counter counterVal
              # retrigger job via API, replace apiToken and 61440 with the id of your runSh job
              curl -X POST -H "Authorization: apiToken 05267c17-ce42-464d-8770-cb34e05b8ee2" -H "Content-Type: application/json" -H "Accept: application/json" "https://api.shippable.com/resources/61440/triggerNewBuildRequest"'
          fi
