resources:
  # Create a key-value pair integration to securely specify the API token
  # http://docs.shippable.com/platform/integration/key-value/
  - name:           api_token
    type:           integration
    integration:    API_TOKEN_INTEGRATION
    
jobs:
  - name: retriable_job
    type: runSh
    allowPublicAccess: true
    steps:
      - IN: api_token
      - TASK:
          runtime:
            options:
              env:
                - MAX_RETRIES: 3
          script:
            # simulate job failure
            - cat phantom_file.sh
    on_failure:
      script: |
        # Check first run
        if [[ -z "${RETRY_COUNTER}" ]]
        then
            RETRY_COUNTER=1
            echo "Rescheduling job on failure"
        else
            echo "Retry attempt# "$RETRY_COUNTER
        fi
        
        if [[ $RETRY_COUNTER <= $MAX_RETRIES ]]
        then
            # increment failure_counter
            let RETRY_COUNTER++
            
            # retrigger job via API
            # replace 62911 with the jobId of your runSh job. To find the jobId, click on the runSh job in the subscription 
            # dashboard and scroll to the bottom of the page.
            sleep 30
            curl -X POST -H "Authorization: apiToken $API_TOKEN" -H "Content-Type: application/json" -H "Accept: application/json" -d "{\"globalEnv\":{\"RETRY_COUNTER\":\"$RETRY_COUNTER\"}}" "https://api.shippable.com/resources/62911/triggerNewBuildRequest"
        else
            echo "Job will not be rescheduled since $MAX_RETRIES count has been reached"
        fi
